services:
  metabase:
    image: metabase/metabase-enterprise:v1.58.x
    environment:
      MB_CONFIG_FILE_PATH: /app/config.yml
      MB_JETTY_PORT: "${MB_PORT}"
      MB_EDITION: "ee"
      MB_SITE_URL: "http://localhost:${MB_PORT}/"
      MB_JWT_SHARED_SECRET: "${MB_JWT_SHARED_SECRET}"
      MB_EMBEDDING_SECRET_KEY: "${MB_EMBEDDING_SECRET_KEY}"
      MB_SETUP_TOKEN: "${MB_PREMIUM_EMBEDDING_TOKEN}"
      MB_PREMIUM_EMBEDDING_TOKEN: "${MB_PREMIUM_EMBEDDING_TOKEN}"
      MB_RUN_MODE: "${MB_RUN_MODE:-}"
      METASTORE_DEV_SERVER_URL: "${METASTORE_DEV_SERVER_URL:-}"
      MB_JWT_IDENTITY_PROVIDER_URI: "http://localhost:${SERVER_PORT}/auth/sso"
      MB_ADMIN_EMAIL: "${MB_ADMIN_EMAIL}"
      MB_ADMIN_FIRST_NAME: "${MB_ADMIN_FIRST_NAME}"
      MB_ADMIN_LAST_NAME: "${MB_ADMIN_LAST_NAME}"
      MB_ADMIN_PASSWORD: "${MB_ADMIN_PASSWORD}"
    healthcheck:
      test: curl --fail -X GET -I "http://localhost:${MB_PORT}/api/health" || exit 1
      interval: 15s
      timeout: 5s
      retries: 10
    ports:
      - "${MB_PORT}:${MB_PORT}"
    volumes:
      - ./metabase/config.yml:/app/config.yml

  setup:
    image: curlimages/curl:latest
    depends_on:
      metabase:
        condition: service_healthy
    environment:
      MB_INSTANCE_URL: "http://metabase:${MB_PORT}"
      MB_ADMIN_EMAIL: "${MB_ADMIN_EMAIL}"
      MB_ADMIN_PASSWORD: "${MB_ADMIN_PASSWORD}"
      MB_DASHBOARD_ID_TO_EMBED: "${MB_DASHBOARD_ID_TO_EMBED}"
    volumes:
      - ./metabase/setup.sh:/setup.sh:ro
    entrypoint: ["/bin/sh", "/setup.sh"]

  server:
    depends_on:
      metabase:
        condition: service_healthy
      setup:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT: "${SERVER_PORT}"
      MB_INSTANCE_URL: "http://localhost:${MB_PORT}"
      MB_JWT_SHARED_SECRET: "${MB_JWT_SHARED_SECRET}"
      MB_EMBEDDING_SECRET_KEY: "${MB_EMBEDDING_SECRET_KEY}"
      MB_DASHBOARD_ID_TO_EMBED: "${MB_DASHBOARD_ID_TO_EMBED}"
      MB_ADMIN_EMAIL: "${MB_ADMIN_EMAIL}"
      MB_ADMIN_FIRST_NAME: "${MB_ADMIN_FIRST_NAME}"
      MB_ADMIN_LAST_NAME: "${MB_ADMIN_LAST_NAME}"
    healthcheck:
      test: curl --fail -X GET -I "http://localhost:${SERVER_PORT}/" || exit 1
      interval: 2s
      timeout: 2s
      retries: 5
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
